from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from monitoring.views import CCTVViewSet, DetectionViewSet # Assuming 'monitoring' is your app name
from django.conf import settings
from django.conf.urls.static import static


router = DefaultRouter()
router.register(r'cctv', CCTVViewSet)
router.register(r'detections', DetectionViewSet) # This line correctly registers your DetectionViewSet

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)), # This includes all URLs generated by the router
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)